gnssanalysis/gn_io/sp3.py

Duplicated epochs should **not** be present in SP3 files. A warning is now logged if any are found. Detecting and *removing* duplicates also allows comparisons to be run on less compliant data.
The actual duplicate check is done on the Pandas DataFrame with `Index.duplicated()`. A quick test suggests this executes in less than 1ms on a typical SP3 file, so is not a performance concern.

NPI-3060 Remove duplicated epochs in SP3 reader (with warning)

---

gnssanalysis/gn_io/sp3.py

As `has_duplicates` is an already a property inside the sp3 dataframe it is literally free. You may argue that `index.duplicated()` before `if` is not a waste  as you still need it to compute `first dupe`, but I could speculate that 99% of sp3 files come without dupes.

Updated sp3 dupe check \w has_duplicates property

---

gnssanalysis/filenames.py
gnssanalysis/gn_download.py

Download functions in auto_download_PPP have wider use. Proposing to incorporate into gnssanalysis.

Move download functions from ginan/scripts/auto_download_PPP to gnssanalysis

---

gnssanalysis/gn_diffaux.py
gnssanalysis/gn_transform.py

+ Fixing the helmert sign for orbit rotation. 
+ changes of stats for STD

fixing stats + residual estimation

---

gnssanalysis/gn_datetime.py
gnssanalysis/gn_io/rinex.py

The existing rinex reading functions unfortunately atrophied over time and there was an failure in the line that extracted the expected column count from the signal header information (maybe due to changes in pandas versions) and then also failed using datetime2j2000 due to the runtime type checking in that function.
I reworked the column detection and then removed the type checking in the datetime2j2000 function (that function still might need love and updated type hints but I started by just deleting the branching because it seemed to have the same code on both branches).
This go the function working on the data I originally cared about but testing on further random data revealed it failed for /LGOW00AUS_S_20212590000_01D_30S_MO.rnx obtained from GA's gnss-data and more generally …

Fix errors in RINEX reading function

---

gnssanalysis/gn_io/sinex.py

Raise a clearer error (referencing the source file if possible) when an empty Sinex header is encountered.

NPI-3290 Clearer error on empty Sinex header

---

gnssanalysis/gn_diffaux.py

User [TYTY666](https://github.com/TYTY666) found that there was an issue in how the SISRE clk difference was being calculated. 
https://github.com/GeoscienceAustralia/gnssanalysis/pull/19
Specifically, we were not converting to metres in the function (even thought there was a comment saying so).
This PR, therefore, multiplies the `clk_diff` variable by the speed of light to convert to it metres. 
The minus sign suggest in the user's PR will be investigated separately

NPI-3311 Fix the clk_diff variable in SISRE function

---

gnssanalysis/gn_datetime.py
gnssanalysis/gn_io/pod.py

On at least one platform (Windows I think) I've seen while working with someone else  `int` can be a 32-bit integer and the conversion from numpy datetime64/timedelta64 objects fail to convert to 32-bit integers (fair enough due to overflow possibilities). But we don't care about the size of the integer, we just want the conversion to work, and so I've changed to explicitly converting to 64-bit integers.
There's generally also some suspicious stuff going on in gn_datetime but I didn't bother looking at it at this stage, just making the minimal changes needed at this stage.

Convert datetimes explicitly to int64 not int

---

gnssanalysis/gn_io/igslog.py
gnssanalysis/gn_io/nanu.py
gnssanalysis/gn_io/sp3.py

We have been testing Python 3.12 and updating various python packages, including Pandas.
There were a number of errors that popped up and these needed to be sorted in this module before we could run our usual operational jobs. 
Therefore, this PR brings changes to various scripts to ensure proper functioning after update to pandas + other packages
The most important changes are:
- removing additional `+` from the `rec_str_list` variable in `meta2sting()`
- changing the `nd.fill()` function to fill with NATs rather than NANs in the `get_bad_sv_from_nanu_df()` function
- splitting out the transformation of `std_df` into individual components as it seems like the `pd.concat` operation isn't playing nicely with the dataframe `attrs`.

NPI-3331 - Update to gnssanalysis for new packages

---

README.md
gnssanalysis/filenames.py
gnssanalysis/gn_diffaux.py
gnssanalysis/gn_io/sp3.py
gnssanalysis/gn_utils.py

- Fixed 'daily' and 'epoch' clock normalisation with compare_clk() when one of the files have missing data;
- Added option to convert sp3 positional nodata values to NaNs.

Fix clock normalisation and convert sp3 position nodata values to NaNs

---

gnssanalysis/gn_download.py

Recently we had an update to the auto_download_PPP.py script over on the Ginan repo. A number of new and useful functions were added there but have a more appropriate home here on `gnssanalysis`. 
This PR transfers some of those useful functions from https://github.com/GeoscienceAustralia/ginan/blob/develop-weekly/scripts/auto_download_PPP.py to`gn_download.py`.
This should be the first in a series of PRs where we slowly move to using the newer download functions. This will include: 
- moving existing utilities that use the old download functions to using the new functions (on gnssanalysis and ginan)
- deleting old functions that have been superseded with new functions
- updating / documenting existing functions that aren't deleted
Happy to discuss this further in the comments of this PR …

NPI-3197 Transfer download functions from ginan repo

---

gnssanalysis/gn_download.py

A quick PR to fix failing pipeline
Remove unnecessary `time` python module to ensure pipelines don't fail

NPI-3197 - Fix to previous transfer functions PR

---

gnssanalysis/gn_io/sp3.py

Previous implementation searched for a slightly incorrect length of data (50 instead of 51 chars), and did this instead of explicitly specifying the expected format (three char chunks which always end with a digit). It also did not allow for `-`, leading negative values to crash the SP3 header parser.

Npi 3430 Fix SP3 header parsing to more robustly handle orbit accuracy values

---

.github/workflows/python-publish.yml

Updating the publish workflow. 
The tag and previous CICD pipeline dependency have been removed, as the publish workflow is runing everytime after the CICD but skipped if not a release. 
It will be to the user to make sure the CICD workflow is successful before creating a release.

update: publish workflow (on publish only)

---

gnssanalysis/gn_datetime.py
gnssanalysis/gn_io/trop.py
tests/test_datetime.py

Ginan outputs to total delay in ztd in every 20 seconds whereas Bernese does it in every one hour.  So here, I am averaging Ginan data over an hour to match it with Bernese ultra-rapid products. Converting to python datetime makes it easier for pandas dataframe.

ZTD cpmparison

---

gnssanalysis/gn_io/blq.py
gnssanalysis/gn_io/sp3.py
gnssanalysis/gn_io/trop.py

- fixed incorrect width of unused columns between data flag values (2 instead of 1). This allows the second prediction flag to be read in.
- Consolidated definitions of columns for maintainability.
- Updated column/index definitions to clearly define a FLAGS index, and specify names of individual flag columns.
- Fixed SP3 output generator to access and output FLAGS data.
- Addressed misalignment bug caused by the combination of CLK nodata value width, and Pandas adding a space between columns. Also applied this fix to POS nodata value, as it appears the same issue would apply there.
- Added handling for missing flag values (conformance to empty strings to avoid outputting nans)
- Added placeholder TODOs for throwing exceptions if record types are encountered that we currently do not …

NPI-3446 Fix SP3 parse and write of data section flags, plus address CLK and POS nodata causing misalignment

---

gnssanalysis/gn_io/clk.py

After trying out the latest candidate Ginan release (v3.1), the attribute error was not very informative when it came up for me.
This is a quick PR to add a message to the assert in the CLK read function - letting the user know that the data is not parsable.

NPI-3485 Add assert message in CLK read function

---

gnssanalysis/gn_io/clk.py
gnssanalysis/gn_io/trace.py

Quick PR to replace the old `np.float_` with `np.float64` in the `clk.py` and `trace.py` IO files.
Some other `black` formatting changes are coming along for the ride as well

NPI-3485 Remove deprecated numpy type

---

gnssanalysis/gn_aux.py
gnssanalysis/gn_diffaux.py
gnssanalysis/gn_download.py
gnssanalysis/gn_io/sp3.py

Transfer SP3 and CLK analysis functions from `ssrMonitoring` to `gnssanalysis`
Transfer `generate_sampling_rate()` from `auto_download_PPP` to `gnssanalysis`

Transfer Ginan-Ops functions

---

gnssanalysis/enum_meta_properties.py
gnssanalysis/solution_types.py
tests/test_solution_type.py

This PR adds utility classes to more formally capture the definitions of solution types defined by IGS. This avoids identifying solution types by short strings throughout the codebase, and allows additional details of each solution type to potentially be captured here as well.

NPI-3458 implement solution types utility classes

---

.github/workflows/python-cicd-units.yml
gnssanalysis/__init__.py
gnssanalysis/_version.py
gnssanalysis/filenames.py
gnssanalysis/gn_aux.py
gnssanalysis/gn_const.py
gnssanalysis/gn_datetime.py
gnssanalysis/gn_diffaux.py
gnssanalysis/gn_download.py
gnssanalysis/gn_frame.py
gnssanalysis/gn_io/discon.py
gnssanalysis/gn_io/erp.py
gnssanalysis/gn_io/ionex.py
gnssanalysis/gn_io/psd.py
gnssanalysis/gn_io/rinex.py
gnssanalysis/gn_io/sinex.py
gnssanalysis/gn_io/sp3.py
gnssanalysis/gn_io/trop.py
gnssanalysis/gn_plot.py
gnssanalysis/gn_utils.py

Changes in the code to make the package compatible for python 3.9 again. 
Python 3.9 is the default install on Apple MacOS, it's end of life is in October 2025. 
Main changes are:
- moved from match/case statement to dictionary (1 occurence)
- moved from the typehint `|` operator to `Union` 
a few other fixes/simplification the time I was doing it.

Restoring backward compatibilities

---

gnssanalysis/gn_io/common.py
gnssanalysis/gn_io/sp3.py
tests/test_common.py

These changes should help to avoid misleading downstream errors caused by empty files, which are currently not detected at the file reading stage.
- `path2bytes()` now raises exceptions on all errors rather than returning None. It also raises an `EOFError` if the input data is empty. It has also been restructured slightly for clarity and type checking.
- `read_sp3()` now accepts a `Path` or `bytes` input in addition to a path as `str`. It now writes an empty string into the 'path' attribute if the input was passed as bytes.

NPI-3501 better empty input file checks

---

gnssanalysis/filenames.py
gnssanalysis/gn_io/common.py
gnssanalysis/gn_io/nanu.py

This addresses a refactoring issue introduced in #54 and published as pre-release `0.0.57.dev1`
It also adds some minor doc/commenting improvements.

NPI-3501 bug fix for issue introduced with improved input checks

---

gnssanalysis/gn_download.py

Add download_iau2000_file() and other improvements

Add download_iau2000_file()

---

gnssanalysis/gn_io/sp3.py

This change:
- Adds checks for SP3 flag values (during SP3 writing).
- Makes datatypes explicit while concatenating flags into a single column for rendering reasons. Hopefully a recent crash related to that will be addressed by this change (see corresponding ticket number for details).

NPI-3547 Attempt to address SP3 flag rendering related crash

---

gnssanalysis/gn_io/sp3.py

No functional changes, but a bunch of renamed variables to hopefully make it clearer what this function is doing.

NPI-3655 Improve readability of getVelPoly() function

---

gnssanalysis/gn_io/igslog.py
tests/test_datasets/sitelog_test_data.py
tests/test_igslog.py

A quick PR to update the code to handle new metadata fields in IGS log files.
This will still be able to read and process the old IGS log files as well (backwards compatible)

NPI-3653 - Update code to handle new V2 IGS logs

---

gnssanalysis/gn_io/sp3.py
tests/test_sp3.py

`gnssanalysis` currently does not correctly support output of SP3 velocity data.
At present, currently calling `gen_sp3_content()` on a `DataFrame` containing velocity data, will result in a non-compliant SP3 file with velocity data in additional columns (not in additional, interlaced rows as the spec calls for).
This PR adds a check for velocity columns. If any velocity columns are found a warning is logged, the columns are deleted, then output continues as normal on just the position data.
Optionally based on a new parameter to `gen_sp3_content()`, a `NotImplementedError` can be raised instead of logging a warning.

NPI-3676 Exception handling on (unsupported) SP3 velocity data output

---

gnssanalysis/gn_io/aux_dicts.py
gnssanalysis/gn_io/igslog.py
tests/test_datasets/sitelog_test_data.py
tests/test_igslog.py

The previous PR on this branch had a couple errors that meant the `write_meta_gather_master()` function (and `gather_metadata()` function) were not working correctly.
Ultimately, the arguments were being fed in the wrong order to the new `extract_...` functions, and therefore an "incorrect version" flag was being shown (because a station Code was being fed in instead).
This PR fixes my initial oversight - arguments are explicitly passed in

NPI-3653 - Fix errors in parsing IGS log updates

---

gnssanalysis/gn_download.py
tests/test_download.py

Separate IAU2000 file variant selection logic from download functionality and improve selection logic to allow passing a date range rather than a single date.

NPI-3689 Restructure IAU2000 download functionality

---

gnssanalysis/gn_diffaux.py
gnssanalysis/gn_io/sinex.py
gnssanalysis/gn_utils.py

**This PR may be a duplicate of: #77 **
This PR reorganises and cleans up some of the clock comparison and sisre calculation code, to improve consistency.
Originally prompted by https://github.com/GeoscienceAustralia/gnssanalysis/pull/19
Previous work addressed in: https://github.com/GeoscienceAustralia/gnssanalysis/pull/23
This PR also includes various type hints and other fixes.

NPI-3438 Restructure clock comparison and sisre functions for consistent arg order

---

gnssanalysis/gn_datetime.py
gnssanalysis/gn_frame.py
gnssanalysis/gn_io/sp3.py
tests/test_datetime.py

Fixes `GPSDate`'s `to_datetime` property, to return a python `datetime` (currently it returns a `date`).
Various other improvements including more constructor options, and more unit tests.
**Note: merge this first (now done): https://github.com/GeoscienceAustralia/gnssanalysis/pull/78**

NPI-3945 Fix GPSDate as_datetime

---

gnssanalysis/gn_io/sinex.py

Set containing a single string, mistakenly defined as a set of characters within that string. This is likely causing valid stypes to be rejected.

NPI-3973 Fix bug in specification of stypes
